import type { INode } from 'n8n-workflow';

/**
 * Builds the node descriptor that `NodeOperationError` and `NodeApiError` expect.
 *
 * The AI tool variant of this node is generated by n8n and runs on a context that does not always
 * expose `getNode`. Calling it unguarded turns a real, reportable failure into a confusing
 * "this.getNode is not a function" raised from inside the error handler itself, so the missing case
 * falls back to a descriptor that carries enough for the error to render.
 */
export function errorNode(context: { getNode?: () => unknown }): INode {
	const getNode = context.getNode;
	if (typeof getNode === 'function') {
		return getNode.call(context) as INode;
	}
	return {
		id: 'typeSafe',
		name: 'TypeSafe',
		type: 'CUSTOM.typeSafe',
		typeVersion: 1,
		position: [0, 0],
		parameters: {},
	};
}
